### ISSUE TITLE
update form, handlebars

### ISSUE THREAD

**Issue by KyleHagad** [xekyle/digiTome#2]
When loading the update story page, none of the existing values for the story populate the form. These values are supposed to be brought in through handlebars.

**Comment by Abourass** [comment]
THey should be displayed via handlebars but they have to be passed via routing, and looked up via mongo. Lets me see if I can find the error

**Comment by KyleHagad** [comment]
Issue Solved.
Problem:
The story data was not being passed through the route
Solution:
declare story in the update story route.
